version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the files
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.html
    - styles/main.css
    - images/*